// `ah` CLI install-to-PATH (PLAN.md Phase 3, item 5).
//
// The `.app` bundle ships the CLI as `Contents/Resources/ah.js` plus a small
// `Contents/Resources/ah` wrapper that execs `node ah.js "$@"`. This installer
// symlinks that wrapper onto the user's PATH (`/usr/local/bin/ah`), falling back
// to `~/.andreys-helper/bin/ah` + a PATH hint when `/usr/local/bin` is not
// writable.
//
// It is deliberately Foundation-only (no AppKit) so it is callable both from the
// in-app action and from the headless `--install-ah` CLI path. When run
// un-bundled (`swift run`), there is no bundled wrapper, so it locates the repo's
// `dist/ah.js` and generates a wrapper in `~/.andreys-helper/bin` to point at.

import Foundation

public enum AhInstaller {
    public struct Result: Sendable {
        public var ok: Bool
        /// Absolute path of the installed `ah` symlink (or the wrapper itself
        /// when no PATH dir was writable).
        public var location: String
        /// Non-nil when the install landed outside a standard PATH dir; tells the
        /// user how to make `ah` resolve.
        public var pathHint: String?
        public var message: String
    }

    static var preferredBinDir: String { "/usr/local/bin" }
    static var fallbackBinDir: String {
        Bootstrap.baseDir.appendingPathComponent("bin", isDirectory: true).path
    }

    /// Locate the runnable `ah.js`. Prefers the bundled Resources copy; when
    /// un-bundled, walks a few candidate dev locations relative to CWD and the
    /// executable so `--install-ah` works from a `swift run`.
    static func locateAhJs() -> String? {
        let fm = FileManager.default
        if let res = Bundle.main.resourceURL?.appendingPathComponent("ah.js").path,
            fm.fileExists(atPath: res) {
            return res
        }
        let cwd = fm.currentDirectoryPath
        let exeDir = Bundle.main.executableURL?.deletingLastPathComponent().path ?? cwd
        var candidates: [String] = []
        for base in [cwd, exeDir] {
            candidates.append(base + "/dist/ah.js")
            candidates.append(base + "/../dist/ah.js")
            candidates.append(base + "/../../dist/ah.js")
            candidates.append(base + "/../../../dist/ah.js")
        }
        for c in candidates {
            let resolved = URL(fileURLWithPath: c).standardizedFileURL.path
            if fm.fileExists(atPath: resolved) { return resolved }
        }
        return nil
    }

    /// The wrapper script to symlink onto PATH. When bundled, this is the shipped
    /// `Resources/ah`. Otherwise a wrapper is generated in `~/.andreys-helper/bin`
    /// pointing at the located `ah.js`.
    static func resolveWrapper() throws -> String {
        let fm = FileManager.default
        if let bundled = Bundle.main.resourceURL?.appendingPathComponent("ah").path,
            fm.fileExists(atPath: bundled) {
            return bundled
        }
        guard let ahJs = locateAhJs() else {
            throw NSError(domain: "AhInstaller", code: 1, userInfo: [
                NSLocalizedDescriptionKey:
                    "could not locate ah.js (build it with `npm run build:cli`)"])
        }
        try fm.createDirectory(atPath: fallbackBinDir, withIntermediateDirectories: true)
        let wrapper = fallbackBinDir + "/ah"
        let script = """
            #!/bin/sh
            # Auto-generated by AndreysOrchestrator — execs the bundled `ah` CLI via node.
            exec /usr/bin/env node "\(ahJs)" "$@"

            """
        try script.write(toFile: wrapper, atomically: true, encoding: .utf8)
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: wrapper)
        return wrapper
    }

    /// Symlink the `ah` wrapper onto PATH. Idempotent (replaces an existing
    /// symlink at the target). Falls back to `~/.andreys-helper/bin` when
    /// `/usr/local/bin` is not writable.
    @discardableResult
    public static func install() -> Result {
        let fm = FileManager.default
        let wrapper: String
        do { wrapper = try resolveWrapper() } catch {
            return Result(ok: false, location: "", pathHint: nil,
                          message: "install failed: \(error.localizedDescription)")
        }

        // Try /usr/local/bin first, else the fallback bin dir.
        for dir in [preferredBinDir, fallbackBinDir] {
            try? fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
            guard fm.isWritableFile(atPath: dir) else { continue }
            let target = dir + "/ah"
            // If the wrapper already lives here, nothing to symlink.
            if URL(fileURLWithPath: target).standardizedFileURL.path
                == URL(fileURLWithPath: wrapper).standardizedFileURL.path {
                return Result(ok: true, location: target,
                              pathHint: pathHintFor(dir),
                              message: "ah already installed at \(target)")
            }
            // Remove any existing entry we own (symlink or stale file).
            if fm.fileExists(atPath: target) || isSymlink(target) {
                try? fm.removeItem(atPath: target)
            }
            do {
                try fm.createSymbolicLink(atPath: target, withDestinationPath: wrapper)
                return Result(ok: true, location: target,
                              pathHint: pathHintFor(dir),
                              message: "installed ah → \(target)")
            } catch {
                continue  // try the next dir
            }
        }

        return Result(ok: false, location: "", pathHint: nil,
                      message: "no writable install dir (tried \(preferredBinDir), \(fallbackBinDir))")
    }

    private static func isSymlink(_ path: String) -> Bool {
        (try? FileManager.default.destinationOfSymbolicLink(atPath: path)) != nil
    }

    /// A PATH hint when the install dir may not be on the user's PATH.
    private static func pathHintFor(_ dir: String) -> String? {
        if dir == preferredBinDir { return nil }
        return "add \(dir) to your PATH, e.g. `export PATH=\"\(dir):$PATH\"`"
    }
}
